The following cache annotations are supported:

- link:{api}/io/micronaut/cache/annotation/Cacheable.html[@Cacheable] - Indicates a method is cacheable within the given cache name
- link:{api}/io/micronaut/cache/annotation/CachePut.html[@CachePut] - Indicates that the return value of a method invocation should be cached. Unlike `@Cacheable` the original operation is never skipped.
- link:{api}/io/micronaut/cache/annotation/CacheInvalidate.html[@CacheInvalidate] - Indicates the invocation of a method should cause the invalidation of one or many caches.

By using one of the annotations the api:cache.interceptor.CacheInterceptor[] is activated which in the case of `@Cacheable` will cache the return result of the method.

[NOTE]
.Cache hits skip method execution
====
When a value is already present for the computed cache key, `@Cacheable` returns the cached value and does not invoke the original method again.

This also applies in tests that reuse the same application context. If multiple test methods use the same cache name and key, later tests may observe values cached by earlier tests unless the cache is invalidated or a different key is used.
====

If the return type of the method is a non-blocking type (either link:{jdkapi}/java.base/java/util/concurrent/CompletableFuture.html[CompletableFuture] or an instance of rs:Publisher[] the emitted result will be cached.

In addition if the underlying Cache implementation supports non-blocking cache operations then cache values will be read from the cache without blocking, resulting in the ability to implement completely non-blocking cache operations.
