To use https://www.ehcache.org/[Ehcache] as the caching implementation, add it as a dependency to your application:

dependency:org.ehcache:ehcache:{ehcacheVersion}[]

To have Micronaut create a cache, the minimum configuration is:

[source,yaml]
----
ehcache:
  caches:
    my-cache:
      enabled: true
----

Then, you can use any of the caching annotations with `my-cache` as cache name.

See the configuration reference to check all possible configuration options.

== Tiering options

Ehcache supports the concept of https://www.ehcache.org/documentation/3.8/tiering.html[tiered caching]. This library
allows you to configure tiering caching options on a per-cache basis.

If no tier is explicitly configured, the cache will be configured with a heap tier of 100 entries maximum.

=== Heap tier

It can be sized by number of entries:

[source,yaml]
----
ehcache:
  caches:
    my-cache:
      heap:
        max-entries: 5000
----

Or by size:

[source,yaml]
----
ehcache:
  caches:
    my-cache:
      heap:
        max-size: 200Mb
----

=== Off-heap tier

[source,yaml]
----
ehcache:
  caches:
    my-cache:
      offheap:
        max-size: 1Gb
----

Do not forget to define in the java options the `-XX:MaxDirectMemorySize` option, according to the off-heap size you
intend to use.

=== Disk tier

[source,yaml]
----
ehcache:
  storage-path: /var/caches
  caches:
    my-cache:
      disk:
        max-size: 10Gb
----