https://hazelcast.org/[Hazelcast] caching is supported. Micronaut will create a Hazelcast client instance to connect to
an existing Hazelcast server cluster.

Add the Micronaut Hazelcast module as a dependency:

dependency:io.micronaut.cache:micronaut-cache-hazelcast:{version}[]

The minimal configuration to use Hazelcast is to simply declare `hazelcast:` with a network configuration for addresses of the
Hazelcast cluster (example below).

[source,yaml]
----
hazelcast:
  network:
    addresses: ['121.0.0.1:5701']
----

When using the link:{api}/io/micronaut/cache/annotation/Cacheable.html[@Cacheable] and other Cache Annotations, Micronaut will create
the Hazelcast client and use the underlying https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/core/IMap.html[IMap] Cache Datastore
on the server.

The full list of configuration options is below. Amongst the list, properties that have default built-in https://docs.micronaut.io/latest/api/io/micronaut/core/convert/TypeConverter.html[TypeConverter] can be set
in YAML.  For example, `hazelcast.network.connectionTimeout` and `hazelcast.network.smart-routing` are primitive types and can be set in YAML files.

For other types, Micronaut users must create a https://docs.micronaut.io/latest/api/io/micronaut/core/convert/TypeConverter.html[TypeConverter] to set the property
in YAML.

include::{includedir}configurationProperties/io.micronaut.cache.hazelcast.HazelcastClientConfiguration.adoc[]

An alternative but more direct option is to create a https://docs.micronaut.io/latest/api/io/micronaut/context/event/BeanCreatedEventListener.html[BeanCreatedEventListener] for
link:{api}/io/micronaut/cache/hazelcast/HazelcastClientConfiguration.html[HazelcastClientConfiguration]. This will be invoked by the
Micronaut Framework on bean creation of `HazelcastClientConfiguration`, and from the event you can programmatically add to the instance. For example:

[source,java]
----
public class HazelcastAdditionalSettings implements BeanCreatedEventListener<HazelcastClientConfiguration> {

    @Override
    public HazelcastClientConfiguration onCreated(BeanCreatedEvent<HazelcastClientConfiguration> event) {
        HazelcastClientConfiguration configuration = event.getBean();
        configuration.getGroupConfig().setName("myName");
    }
}
----
