CREATE TABLE MN_CACHE_ENTRY (
    CACHE_NAME VARCHAR2(255) NOT NULL,
    KEY_HASH RAW(32) NOT NULL,
    KEY_PAYLOAD BLOB NOT NULL,
    VALUE_PAYLOAD BLOB,
    VALUE_WEIGHT NUMBER(19, 0),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    LAST_ACCESS_AT TIMESTAMP(6),
    EXPIRES_AT TIMESTAMP(6),
    CONSTRAINT MN_CACHE_ENTRY_PK PRIMARY KEY (CACHE_NAME, KEY_HASH, KEY_PAYLOAD)
);

CREATE TABLE MN_CACHE_CONFIG (
    CACHE_NAME VARCHAR2(255) NOT NULL,
    BLOCKING NUMBER(1, 0) DEFAULT 0 NOT NULL,
    LOCK_WAIT_TIMEOUT_MS NUMBER(19, 0) DEFAULT 5000 NOT NULL,
    CLEANUP_INTERVAL_SECONDS NUMBER(19, 0) DEFAULT 60 NOT NULL,
    MAXIMUM_SIZE NUMBER(19, 0),
    MAXIMUM_WEIGHT NUMBER(19, 0),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT MN_CACHE_CONFIG_PK PRIMARY KEY (CACHE_NAME)
);

CREATE TABLE MN_CACHE_STATS (
    CACHE_NAME VARCHAR2(255) NOT NULL,
    HIT_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    MISS_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    PUT_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    INVALIDATE_COUNT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    CURRENT_SIZE NUMBER(19, 0) DEFAULT 0 NOT NULL,
    CURRENT_WEIGHT NUMBER(19, 0) DEFAULT 0 NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    CONSTRAINT MN_CACHE_STATS_PK PRIMARY KEY (CACHE_NAME)
);

CREATE INDEX MN_CACHE_ENTRY_EXPIRES_IDX ON MN_CACHE_ENTRY (CACHE_NAME, EXPIRES_AT);

CREATE INDEX MN_CACHE_ENTRY_ACCESS_IDX ON MN_CACHE_ENTRY (CACHE_NAME, LAST_ACCESS_AT, CREATED_AT);

CREATE OR REPLACE PROCEDURE MN_CACHE_CLEANUP_CACHE(
    P_CACHE_NAME IN VARCHAR2,
    P_BATCH_SIZE IN NUMBER
) AS
    V_MAX_SIZE NUMBER;
    V_MAX_WEIGHT NUMBER;
    V_CURRENT_SIZE NUMBER;
    V_CURRENT_WEIGHT NUMBER;
BEGIN
    DELETE FROM MN_CACHE_ENTRY
    WHERE CACHE_NAME = P_CACHE_NAME
      AND EXPIRES_AT IS NOT NULL
      AND EXPIRES_AT < SYSTIMESTAMP;

    BEGIN
        SELECT MAXIMUM_SIZE, MAXIMUM_WEIGHT
        INTO V_MAX_SIZE, V_MAX_WEIGHT
        FROM MN_CACHE_CONFIG
        WHERE CACHE_NAME = P_CACHE_NAME;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_MAX_SIZE := NULL;
            V_MAX_WEIGHT := NULL;
    END;

    IF V_MAX_SIZE IS NOT NULL THEN
        LOOP
            SELECT COUNT(*)
            INTO V_CURRENT_SIZE
            FROM MN_CACHE_ENTRY
            WHERE CACHE_NAME = P_CACHE_NAME;
            EXIT WHEN V_CURRENT_SIZE <= V_MAX_SIZE;
            DELETE FROM MN_CACHE_ENTRY
            WHERE ROWID IN (
                SELECT ROWID
                FROM MN_CACHE_ENTRY
                WHERE CACHE_NAME = P_CACHE_NAME
                ORDER BY NVL(LAST_ACCESS_AT, CREATED_AT), CREATED_AT, KEY_HASH
                FETCH FIRST P_BATCH_SIZE ROWS ONLY
            );
            EXIT WHEN SQL%ROWCOUNT = 0;
        END LOOP;
    END IF;

    IF V_MAX_WEIGHT IS NOT NULL THEN
        LOOP
            SELECT NVL(SUM(VALUE_WEIGHT), 0)
            INTO V_CURRENT_WEIGHT
            FROM MN_CACHE_ENTRY
            WHERE CACHE_NAME = P_CACHE_NAME;
            EXIT WHEN V_CURRENT_WEIGHT <= V_MAX_WEIGHT;
            DELETE FROM MN_CACHE_ENTRY
            WHERE ROWID IN (
                SELECT ROWID
                FROM MN_CACHE_ENTRY
                WHERE CACHE_NAME = P_CACHE_NAME
                ORDER BY NVL(LAST_ACCESS_AT, CREATED_AT), CREATED_AT, KEY_HASH
                FETCH FIRST P_BATCH_SIZE ROWS ONLY
            );
            EXIT WHEN SQL%ROWCOUNT = 0;
        END LOOP;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE MN_CACHE_REGISTER_CLEANUP_JOB(
    P_CACHE_NAME IN VARCHAR2,
    P_INTERVAL_SECONDS IN NUMBER
) AS
    V_JOB_NAME VARCHAR2(128);
    V_EXISTS NUMBER;
    V_INTERVAL NUMBER;
    V_ACTION VARCHAR2(4000);
BEGIN
    V_INTERVAL := GREATEST(1, NVL(P_INTERVAL_SECONDS, 60));
    V_JOB_NAME := 'MN_CACHE_CLEANUP_' || SUBSTR(RAWTOHEX(STANDARD_HASH(P_CACHE_NAME, 'SHA1')), 1, 20);
    V_ACTION := 'BEGIN MN_CACHE_CLEANUP_CACHE(''' || REPLACE(P_CACHE_NAME, '''', '''''') || ''', 100); END;';

    SELECT COUNT(1)
    INTO V_EXISTS
    FROM USER_SCHEDULER_JOBS
    WHERE JOB_NAME = V_JOB_NAME;

    IF V_EXISTS = 0 THEN
        DBMS_SCHEDULER.CREATE_JOB(
            JOB_NAME => V_JOB_NAME,
            JOB_TYPE => 'PLSQL_BLOCK',
            JOB_ACTION => V_ACTION,
            START_DATE => SYSTIMESTAMP,
            REPEAT_INTERVAL => 'FREQ=SECONDLY;INTERVAL=' || TO_CHAR(V_INTERVAL),
            ENABLED => FALSE,
            AUTO_DROP => FALSE
        );
    ELSE
        DBMS_SCHEDULER.SET_ATTRIBUTE(V_JOB_NAME, 'job_action', V_ACTION);
        DBMS_SCHEDULER.SET_ATTRIBUTE(V_JOB_NAME, 'repeat_interval', 'FREQ=SECONDLY;INTERVAL=' || TO_CHAR(V_INTERVAL));
    END IF;

    DBMS_SCHEDULER.ENABLE(V_JOB_NAME);
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -27477 THEN
            DBMS_SCHEDULER.SET_ATTRIBUTE(V_JOB_NAME, 'repeat_interval', 'FREQ=SECONDLY;INTERVAL=' || TO_CHAR(V_INTERVAL));
            DBMS_SCHEDULER.ENABLE(V_JOB_NAME);
        ELSE
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE PROCEDURE MN_CACHE_PUT_BLOCKING(
    P_CACHE_NAME IN VARCHAR2,
    P_KEY_HASH IN RAW,
    P_KEY_PAYLOAD IN BLOB,
    P_VALUE_PAYLOAD IN BLOB,
    P_EXPIRES_AT IN TIMESTAMP,
    P_VALUE_WEIGHT IN NUMBER,
    P_STATUS OUT VARCHAR2
) AS
    V_NOW TIMESTAMP(6) := CAST(SYSTIMESTAMP AT TIME ZONE 'UTC' AS TIMESTAMP);
BEGIN
    P_STATUS := 'ERROR';

    INSERT INTO MN_CACHE_ENTRY (
        CACHE_NAME,
        KEY_HASH,
        KEY_PAYLOAD,
        VALUE_PAYLOAD,
        VALUE_WEIGHT,
        CREATED_AT,
        LAST_ACCESS_AT,
        EXPIRES_AT
    ) VALUES (
        P_CACHE_NAME,
        P_KEY_HASH,
        P_KEY_PAYLOAD,
        NULL,
        NVL(P_VALUE_WEIGHT, 1),
        V_NOW,
        V_NOW,
        P_EXPIRES_AT
    );

    UPDATE MN_CACHE_ENTRY
       SET VALUE_PAYLOAD = P_VALUE_PAYLOAD,
           VALUE_WEIGHT = NVL(P_VALUE_WEIGHT, 1),
           LAST_ACCESS_AT = V_NOW,
           EXPIRES_AT = P_EXPIRES_AT
     WHERE CACHE_NAME = P_CACHE_NAME
       AND KEY_HASH = P_KEY_HASH
       AND KEY_PAYLOAD = P_KEY_PAYLOAD;

    P_STATUS := 'SUCCESS';
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        P_STATUS := 'ALREADY_INSERTED';
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/
