WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER=TESTPDB;

DECLARE
    V_EXISTS NUMBER := 0;
BEGIN
    FOR I IN 1..60 LOOP
        SELECT COUNT(1)
        INTO V_EXISTS
        FROM ALL_USERS
        WHERE USERNAME = 'TEST_USER';

        EXIT WHEN V_EXISTS = 1;
        DBMS_LOCK.SLEEP(1);
    END LOOP;

    IF V_EXISTS = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'TEST_USER was not created in TESTPDB within timeout');
    END IF;
END;
/

GRANT CREATE JOB TO TEST_USER;
GRANT EXECUTE ON DBMS_SCHEDULER TO TEST_USER;

EXIT;
